name: LoadingViewExample

options:
  bundleIdPrefix: dev.jano.loadingView
  usesTabs: false
  indentWidth: 4
  tabWidth: 4
  createIntermediateGroups: true
  deploymentTarget:
    iOS: 17.0

settings:
    CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: YES
    DEVELOPMENT_TEAM: PPSF6CNP8Q

packages:

  LoadingView:
    path: .

targets:

  LoadingViewExample:
    type: application
    platform: iOS
    settings:
      CURRENT_PROJECT_VERSION: 1
      MARKETING_VERSION: 1.0.0
      INFOPLIST_FILE: Example/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: dev.jano.loadingView.example
      PRODUCT_NAME: LoadingViewExample
    sources: Example
    dependencies:
      - package: LoadingView
